Added version number to the footer
upscayl/upscayl pull request #274
Opened 2023-04-15 03:44 UTC by AyliasTheCoder

Added the version number to the footer to address issue #228

2023-04-15 03:55 UTC, NayamAmarshe commented
Thanks a lot for the PR! Could you please add a screenshot so I can take a look?

2023-04-15 04:27 UTC, AyliasTheCoder commented
![image](https://user-images.githubusercontent.com/79167674/232182835-a0907c07-9336-41ff-877b-dd978712e95c.png)

2023-04-15 04:35 UTC, AyliasTheCoder commented
I updates it to be inline with the rest of the text

2023-04-15 04:36 UTC, AyliasTheCoder commented
I updated it to be inline with the rest of the footer

![image](https://user-images.githubusercontent.com/79167674/232183114-38c6dc15-23bb-4f7b-acca-cc92a4f6b321.png)

2023-04-15 05:22 UTC, NayamAmarshe requested changes

2023-04-15 05:22 UTC, NayamAmarshe commented on renderer/components/Footer.tsx
> +import packageJSON from "../../package.json";
Interesting that you directly imported the version from `package.json`, it's a nice idea. While it works, I think importing the whole JSON file might be a bit unnecessary.

If you take a look at index.tsx page, we're using the following snippet to fetch the app version: `setVersion(navigator?.userAgent?.match(/Upscayl\/([\d\.]+\d+)/)[1]);`. This makes sure that we're only using what we need and not importing the whole package.json (which might or might not be available during the build step).

2023-04-15 05:22 UTC, NayamAmarshe commented on renderer/components/Footer.tsx
> +        (version <span className="font-bold">{packageJSON.version}</span>)
```suggestion
        (v<span className="font-bold">{navigator?.userAgent?.match(/Upscayl\/([\d\.]+\d+)/)[1]}</span>)
```

2023-04-15 05:38 UTC, NayamAmarshe commented on renderer/components/Footer.tsx
> +import packageJSON from "../../package.json";
```suggestion
```

2023-04-15 05:38 UTC, NayamAmarshe commented on renderer/components/Footer.tsx
> +import packageJSON from "../../package.json";
Just one last import to be removed :)

2023-04-15 06:14 UTC, NayamAmarshe commented
Looks good! Thanks😁

2023-04-15 06:14 UTC, merged

2023-04-16 02:20 UTC, NayamAmarshe commented
Well, I'd have to unfortunately undo these changes because I forgot I already added a version in the header. We don't need another in footer 😅