fixed react infinite loop on adding single image
upscayl/upscayl pull request #297
Opened 2023-05-02 04:43 UTC by yevgeniyakimenko

created a couple of extra state variables to avoid calling `formatPath` directly

2023-05-02 06:40 UTC, NayamAmarshe requested changes

2023-05-02 06:40 UTC, NayamAmarshe commented on renderer/pages/index.tsx
> +  const [formattedUpscaledImagePath, setFormattedUpscaledImagePath] = useState("");
I think instead of doing this, we could directly use formatPath on the setImagePath and setUpscaledImagePath.

2023-05-02 06:40 UTC, NayamAmarshe commented on renderer/pages/index.tsx
> +      setFormattedUpscaledImagePath(formatPath(data));
```suggestion
      setUpscaledImagePath(formatPath(data));
```

2023-05-02 06:40 UTC, NayamAmarshe commented on renderer/pages/index.tsx
> +      setFormattedUpscaledImagePath(formatPath(data));
```suggestion
      setUpscaledImagePath(formatPath(data));
      logit("upscaledImagePath: ", upscaledImagePath);
```

2023-05-02 06:40 UTC, NayamAmarshe commented on renderer/pages/index.tsx
> +      setFormattedImagePath(formatPath(path));
```suggestion
      SetImagePath(formatPath(path));
```

2023-05-02 06:40 UTC, NayamAmarshe commented on renderer/pages/index.tsx
> +        setFormattedImagePath(formatPath(filePath));
```suggestion
        SetImagePath(formatPath(filePath));
```

2023-05-02 06:40 UTC, NayamAmarshe commented on renderer/pages/index.tsx
> +      setFormattedImagePath(formatPath(filePath));
```suggestion
      SetImagePath(formatPath(filePath));
```

2023-05-02 06:40 UTC, NayamAmarshe commented on renderer/pages/index.tsx
> +                      : formattedImagePath
```suggestion
                      ? upscaledImagePath
                      : imagePath
```

2023-05-02 06:40 UTC, NayamAmarshe commented on renderer/pages/index.tsx
> +                      src={"file:///" + formattedImagePath}
```suggestion
                      src={"file:///" + imagePath}
```

2023-05-02 06:40 UTC, NayamAmarshe commented on renderer/pages/index.tsx
> +                      src={"file://" + formattedUpscaledImagePath}
```suggestion
                      src={"file://" + upscaledImagePath}
```

2023-05-02 19:28 UTC, aaronliu0130 commented
@TGS963 has went ahead and removed usages of `formatpath` entirely in cc0597a.

2023-05-02 20:08 UTC, aaronliu0130 commented
You could press "Add suggestion to batch" in the files tab and just commit all of them at once.

2023-05-02 20:12 UTC, yevgeniyakimenko commented
Thank you, all of these seem to be wiser choices.

2023-05-02 21:30 UTC, NayamAmarshe commented
This requires some more looking into.
I tried the changes mentioned in the branch and it did not work for me for some strange reason.

The way react is handling `src` seems weird. I'll have to take a look into it.

2023-05-02 22:35 UTC, aaronliu0130 commented
Does the main branch currently work?

2023-05-03 04:08 UTC, yevgeniyakimenko commented
@NayamAmarshe  Shall I delete the PR?

2023-05-03 04:13 UTC, TGS963 commented
The suggested changes do work but many models do not function with URI encoded filenames. So we cannot have the imagePath becoming an URI encoded string. The only alternative I have found right now, is to directly call the regex function in the src which makes the code look ugly and is redundant.

2023-05-03 04:16 UTC, TGS963 commented
> Does the main branch currently work?

yes it does

2023-05-03 09:46 UTC, NayamAmarshe commented
> The suggested changes do work but many models do not function with URI encoded filenames. So we cannot have the imagePath becoming an URI encoded string. The only alternative I have found right now, is to directly call the regex function in the src which makes the code look ugly and is redundant.
> 
> Another would be to use separate states for formattedImagePath which was the initial commit on this PR anyway

Okay, it's fine to use regex directly if it's working with all the models.

2023-05-03 17:38 UTC, TGS963 commented
@yevgeniyakimenko You can put the regex directly inside the src. Make that change and we can merge :)

2023-05-04 01:18 UTC, yevgeniyakimenko commented
@TGS963 Thanks! hould I also remove the formatPath function?

2023-05-04 02:15 UTC, NayamAmarshe commented
> @TGS963 Thanks! should I also remove the formatPath function?

Yes

2023-05-04 02:20 UTC, TGS963 commented
> @TGS963 Thanks! should I also remove the formatPath function?

Yes, also replace the line with

`` `${upscaledImagePath ? upscaledImagePath : imagePath}` ``

and put the regex expression after the ternary values as well

2023-05-04 19:02 UTC, yevgeniyakimenko commented
done

2023-05-04 19:04 UTC, TGS963 commented
Great work! We will merge the PR after reviewing and checking one more time

2023-05-05 14:53 UTC, TGS963 commented
Great work, I have verified everything to be working great in the latest commit. I will merge the PR now. Thanks for your contribution! :D

2023-05-05 14:53 UTC, merged