[WIP] Initial notification icon support
upscayl/upscayl pull request #710
Opened 2024-02-12 12:44 UTC by MrPenguin07

As icon locations are platform dependent, iterate through paths & add to notification util. 
Confirmed working well for linux(deb/rpm), AppImage & Windows platforms.

Todo:
- Confirm mac & flatpak icon paths are correct (i'm unable to test)
@aaronliu0130 appreciate if you're able to test. 

**Before and after shots:**

Linux notifications:
![upscayl-notif-linux](https://github.com/upscayl/upscayl/assets/127086564/4f98257f-0a1c-4ce1-a346-914b1e46fd0c)
(bottom before, top after)

Windows:
![upscayl-win-notif](https://github.com/upscayl/upscayl/assets/127086564/1aa5ffb6-c907-4493-97de-ee1b99a627e9)

Win.

2024-02-12 15:15 UTC, aaronliu0130 commented
Doesn't resources/128x128.png always exist relative to the file regardless of system?

2024-02-12 23:23 UTC, MrPenguin07 commented
> Doesn't resources/128x128.png always exist regardless of system?

In my testing... it does not

2024-02-13 02:39 UTC, MrPenguin07 commented
> Maybe it has to be a ./? I currently don't have access to my Arch laptop so I can't test it yet

You mean as below?
```
  const iconPaths = [
    "./resources/128x128.png",
  ];
  ```
  As much as i'd love that simplicity to be true, confirming this doesn't work for AppImage (and I suspect others).

2024-02-13 02:41 UTC, aaronliu0130 commented
Hmm, maybe it's only an AppImage thing? https://github.com/AppImage/AppImageKit/issues/1035

2024-02-13 03:21 UTC, MrPenguin07 commented
> Hmm, maybe it's only an AppImage thing? [AppImage/AppImageKit#1035](https://github.com/AppImage/AppImageKit/issues/1035)
> 
> I'd suspect the `./` to have no actual effect here.

There very well may be an appimage variable or some such to the icon however confirming that `resources/128x128.png` will not work it would require an extra path in the array regardless.
The path prefixed with `__appImage-x64` works - and is unlikely to change? - so may not be worth the headache looking further :)

Can confirm the deb/rpm work simply with `resources/128x128.png` however again i'd hesitate to rely on that, package managers may not retain an otherwise redundant icon (especially since we fixed #680 ) in future. 
So an extra path to the freedesktop icon spec location under `/usr/share/icons` is wise.

Windows I believe does use `resources/128x128.png`.

So this justifies my thought process in hardcoding a handful of paths, for redundancy and simplicity.


_The flatpak and mac builds i'm curious about, would appreciate feedback from someone who can test these._

2024-05-15 09:17 UTC, MrPenguin07 commented
So would appreciate some input on this; 
What exactly needs be done to merge this?
Needs more emoji?!

I've confirmed this PR works on majority of builds - even if it didn't work, for eg., on the mac build the notification would still show same as without the PR.

2024-05-15 10:17 UTC, NayamAmarshe commented
> So would appreciate some input on this; What exactly needs be done to merge this? Needs more emoji?!
> 
> I've confirmed this PR works on majority of builds - even if it didn't work, for eg., on the mac build the notification would still show same as without the PR.

The PR was in draft, I thought you were still working on it.

2024-05-15 10:19 UTC, NayamAmarshe requested changes
LGTM! We just need to update one thing :)

2024-05-15 10:19 UTC, NayamAmarshe commented on electron/utils/show-notification.ts
> +import * as fs from 'fs';
```suggestion
import fs from 'fs';
```

2024-05-15 10:19 UTC, merged

2024-05-15 20:20 UTC, MrPenguin07 commented
> The PR was in draft, I thought you were still working on it.

Just hoped someone could test it for mac/flatpak :)
Cheers

2024-05-15 22:12 UTC, aaronliu0130 commented
Continuing discussion in b2a3e54dfc374b674a4fe52664e0c4be80b27f9d